# 3-8 Seeing the World
where_is_my_mind = ["london", "osaka", "tokio", "budapest", "edinburgh"]
print(where_is_my_mind)
print(sorted(where_is_my_mind))
print(where_is_my_mind)
print(sorted(where_is_my_mind, reverse=True))
print(where_is_my_mind)
where_is_my_mind.reverse()
print(where_is_my_mind)
where_is_my_mind.reverse()
print(where_is_my_mind)
where_is_my_mind.sort()
print(where_is_my_mind)
where_is_my_mind.sort(reverse=True)
print(where_is_my_mind)
