# 3-10 Every Function
listo = ["hi", "hello", "greetings", "heyo", "wazzup"]
print(listo)
print(listo[1].title())
print(listo[-1])
print(f"x got nothing going on, so hey {listo[-1].title()}")
listo[0] = "konnichiwa"
print(listo)
listo.append("bonjour")
print(listo)
listo.insert(0, "ayo")
print(listo)
del listo[-2]
print(listo)
ggwp = listo.pop()
print(ggwp)
print(f"I don't like the word {ggwp}")
print(listo)
listo.remove("ayo")
print(listo)
notok = "heyo"
listo.remove(notok)
print(listo)
print(f"{notok} is not hip enough for me")
print(listo)
listo.sort()
print(listo)
listo.sort(reverse=True)
print(listo)
print(sorted(listo))
print(sorted(listo, reverse=True))
listo.append("wazzzuhhhh")
listo.reverse()  # reverses the list as is
print(listo)
listo.reverse()
print(listo)
print(len(listo))
